"""Update tabla objetivos: cambio de monto y tipo por nuevos campos

Revision ID: 7934c1a71f00
Revises: 
Create Date: 2024-12-26 15:59:02.089746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7934c1a71f00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objetivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('porcentaje_sueldo', sa.Float(), nullable=False),
    sa.Column('sueldo_base', sa.Float(), nullable=False),
    sa.Column('mes', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reglas_categorizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expresion_regular', sa.String(length=255), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reglas_identificacion_bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expresion_regular', sa.String(length=255), nullable=False),
    sa.Column('banco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('banco_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacciones')
    op.drop_table('reglas_identificacion_bancos')
    op.drop_table('reglas_categorizacion')
    op.drop_table('objetivos')
    op.drop_table('auditorias')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    op.drop_table('bancos')
    # ### end Alembic commands ###
